#49 + 8 hyphens
print("\n\t---------------------------------------------------------")
print("\t|\t\t\tMy CV\t\t\t\t|")
print("\t---------------------------------------------------------")
print("\t|Name\t\t\t| Ssemmambo Ibrahim Kirabo\t|")
print("\t---------------------------------------------------------")
print("\t|Title\t\t\t| Software Engineer\t\t|")
print("\t---------------------------------------------------------")
print("\t|Profile\t\t| I am harmless\t\t\t|")
print("\t---------------------------------------------------------")
print("\t|Education\t\t| Bsc. Computer Science\t\t|")
print("\t---------------------------------------------------------")
print("\t|Hobbies\t\t| Animes, Novel Reading\t\t|")
print("\t---------------------------------------------------------")
print("\t|Languages\t\t| English, Arabic\t\t|")
print("\t---------------------------------------------------------")
